### ISSUE TITLE
Unable to Search for Unassign tickets

### ISSUE THREAD

**Issue by HymaKanchiAU** [aehrc/snomio#282]
Navigate to https://dev-snomio.ihtsdotools.org/dashboard/tickets/backlog
In the Search option type Assignee:Unassign

Actual: Does not show any tickets 
![image](https://github.com/aehrc/snomio/assets/126848487/080db040-7ce1-4e8c-8adc-6eaed08a6d68)

Expected: Should display the tickets where Assignee = Unassign

**Comment by ChrisKellaleaMaynard** [comment]
@clinnygee  please advise whether this is the correct approach for searching for unassigned tickets.
We need to document the advanced searching techniques; if the process doe searching for unassigned tickets is particularly difficult then because it is such a common task we may need to add on-screen buttons to make it an easier process.

**Comment by clinnygee** [comment]
@ChrisKellaleaMaynard Hey, there is currently not a way to search for unassigned tickets. I'm not sure how to go about this immediately - I will have to do some investigation. QueryDSL (which is the DSL we are using for querying jpa) doesn't support null values out of the box, so I will have to look into how to do it.

**Comment by clinnygee** [comment]
Hello. To search assignee:null

**Comment by HymaKanchiAU** [comment]
Able to search for Unassigned tickets in backlog over all the pages.
Total entries were 49466 and when searched for Assignee:null displayed 49438 entries

![Image](https://github.com/aehrc/snomio/assets/126848487/b927fbb6-4223-4b49-955d-9c3783fd438f)

retested this defect and passed
