### ISSUE TITLE
Discuss approach for ordering of packages, products, and ingredients within atomic data entry form

### ISSUE THREAD

**Issue by ChrisKellaleaMaynard** [aehrc/snomio#367]
### Related Issues
* #3 

Topics to be discussed:
1. The order of new items as they are being added to the form: should the new item appear at the bottom of the list, or should sorting automatically occur?
2. How to manipulate the order of these elements on-screen.
3. Where to save the orders within the payload.
4. Where to save the orders within Snowstorm.
5. How to display elements after loading existing data, when the orders are not specified.
6. Whether a reordering will cause Snowstorm to require reclassification and/or revalidation, and whether we want that to occur.
7. How to ensure the LLM for name generation is being passed the elements in the correct order so it can determine the most appropriate PT/FSN.
8. How to handle the retirement/replacement of an element, which may occur independently within AP.

**Comment by lukeswindale** [comment]
1.  Stick with the existing convention and add to the bottom of list. Auto sort may confuse things and prove fiddly when not already completely filled in the data
2.  Using a MUI draggable data grid (https://mui.com/x/react-data-grid/row-ordering/)
3. ** TBC If snowstorm garuantees that order is kept within an axiom (pretty sure it will), then the order is implied by the order they are detailed within the axiom. Otherwise we need to store it within snomio (not desirable)
4. ** TBC If snowstorm garuantees that order is kept within an axiom (pretty sure it will), then the order is implied by the order they are detailed within the axiom. Otherwise we need to store it within snomio (not desirable)
5. Just load them in the order defined within the axiom. The order can be further modified if it's not correct
6. It shouldn't. The axiom ordering doesn't affect the definition of the concept. Probs don't want to kick classifier
7. It will be given a PT substituted axiom, which contains ordering. The LLM just needs to be prompted to keep order for PT and whatever for FSN
8. I don't believe this is an issue, given that we will likely be storing the order, within the axiom, within Snowstorm

**Comment by lukeswindale** [comment]
**Update:**

So we cannot rely on axiom or relationship ordering within snowstorm. This is probably reasonable as they shouldn't care about order. The obvious alternative is to store axiom order in the "component annotation refset". This could be achieved by interacting either directly with the refset endpoint ({snowstorm}/{branch}/members/*) or via a PUT operation through the concept endpoint ({snowstorm}/browser/{branch}/concepts/{conceptid}), as per the example body below. I suspect the latter introduces unnecessary load when we're not really updating the concept (?). We would then get that annotation back when we do a GET on that same endpoint, so we could use the specified ordering when constructing the axiom, for name generation.

`curl --location --request PUT 'https://uat-snowstorm.ihtsdotools.org/snowstorm/snomed-ct/browser/MAIN/SNOMEDCT-AU/AU/concepts/669361000168106' \
--header 'Accept-Language: en-X-900000000000509007,en-X-900000000000508004,en' \
--header 'Content-Type: application/json' \
--data '{
    "conceptId": "669361000168106",
    "fsn": {
        "term": "Wheat dextrin (substance)",
        "lang": "en"
    },
    "pt": {
        "term": "Wheat dextrin",
        "lang": "en"
    },
    "active": true,
    "effectiveTime": "20240328",
    "released": true,
    "releasedEffectiveTime": 20160131,
    "moduleId": "32506021000036107",
    "definitionStatus": "PRIMITIVE",
    "descriptions": [
        {
            "active": true,
            "moduleId": "900000000000207008",
          ...
    ],
    "annotations": [{        
      "value": "{AXIOM_ORDER:[116680003|37202001,116680003|412071004,116680003|2331003]}",
      "conceptId":"669361000168106"
      }
    ],
    "classAxioms": [
       ...
}'`

**Comment by lukeswindale** [comment]
if there's a default, predictable order, we can use that .... unless the concept is annotated otherwise. This is my recommendation unless something better comes along, as I think its the only solution that keeps the ordering with the terminology.
